include:
  - project: mosaik/templates/ci-cd-templates
    file: main-develop.yml
    inputs:
      package: mosaik
      main_branch: master
      develop_branch: develop

Linting:
  script:
    - FORCE_COLOR=1 uvx --from ruff==0.15.22 ruff check
    - uvx --from ruff==0.15.22 ruff check -e --output-format=gitlab -o lintreport.json

Formatting:
  script:
    - uvx --from ruff==0.15.22 ruff format --diff

# Execute the pipeline from the mosaik demo project
mosaik demo:
  stage: Tests
  variables:
    UPSTREAM_BRANCH: $CI_COMMIT_REF_NAME # pass the branch name to the downstream pipeline to check out the correct mosaik version
  trigger:
    project: mosaik/examples/mosaik-demo
    branch: master
  rules:
    - if: $CI_COMMIT_TAG
    - when: manual
      allow_failure: true
