from typing import (
    Any,
    Callable,
    Generic,
    Iterable,
    Iterator,
    Literal,
    TypeVar,
    overload,
)

_N = TypeVar("_N")
_K = TypeVar("_K")

class NodeView(Generic[_N]):
    def __call__(self, data: Literal[True]) -> Any: ...
    def __getitem__(self, node: _N) -> dict[str, Any]: ...
    def __iter__(self) -> Iterator[_N]: ...
    def get(self, node: _N, default: dict[str, Any]) -> dict[str, Any]: ...

class Graph(Generic[_N]):
    def add_edge(self, u_of_edge: _N, v_of_edge: _N, **attr: Any) -> None: ...
    def add_node(self, node: _N, **attr: Any) -> None: ...
    @property
    def nodes(self) -> NodeView[_N]: ...
    @property
    def edges(self) -> Any: ...
    def __getitem__(self, node: _N) -> _N: ...
    def __contains__(self, node: _N) -> bool: ...

class DiGraph(Generic[_N]):
    def add_node(self, node_for_adding: _N, **attr: Any) -> None: ...
    def add_edge(self, u_of_edge: _N, v_of_edge: _N, **attr: Any) -> None: ...
    def has_edge(self, u: _N, v: _N) -> bool: ...
    @overload
    def edges(self, data: Literal[True]) -> Iterable[tuple[_N, _N, dict[str, Any]]]: ...
    @overload
    def edges(self) -> Iterable[tuple[_N, _N]]: ...
    def __getitem__(self, n: _N) -> dict[_N, dict[str, Any]]: ...
    @property
    def nodes(self) -> NodeView[_N]: ...
    def predecessors(self, node: _N) -> Iterable[_N]: ...
    @property
    def adj(self) -> dict[_N, dict[_N, dict[str, Any]]]: ...

class MultiDiGraph(Generic[_N, _K]):
    def add_node(self, node_for_adding: _N) -> None: ...
    def add_edge(self, u_for_edge: _N, v_for_edge: _N, key: _K, **attr: Any) -> _K: ...
    def out_edges(
        self, node: _N, keys: Literal[True], data: Literal[True]
    ) -> Iterable[tuple[_N, _N, _K, dict[str, Any]]]: ...
    def edges(self, data: Literal[True]) -> Iterable[tuple[_N, _N, dict[str, Any]]]: ...

def ancestors(graph: DiGraph[_N], node: _N) -> Iterable[_N]: ...
def shortest_path_length(
    graph: DiGraph[_N], source: _N, target: _N, weight: str
) -> Any: ...
def parse_edgelist(
    lines: Iterable[str],
    create_using: DiGraph[_N],
    nodetype: Callable[[str], _N],
    data: tuple[()],
) -> DiGraph[_N]: ...
def simple_cycles(graph: DiGraph[_N]) -> Iterable[Iterable[_N]]: ...
def spring_layout(graph: DiGraph[_N]) -> dict[_N, tuple[float, float]]: ...
