from collections.abc import Iterable
from typing import Any, Literal

from compute import Expression

type DataType = Literal["int8", "int64", "double"]

def int8() -> Literal["int8"]: ...
def int64() -> Literal["int64"]: ...
def float64() -> Literal["double"]: ...

class Table:
    def join(
        self,
        right_side: Table,
        *,
        keys: str | list[str],
        right_keys: str | list[str],
        join_type: Literal["inner"],
    ) -> Table: ...
    def column(self, name: str) -> Array: ...
    def add_column(self, pos: int, name: str, values: Array) -> Table: ...
    def drop_columns(self, names: str | list[str]) -> Table: ...
    @classmethod
    def from_batches(cls, batches: list[RecordBatch]) -> Table: ...
    def filter(self, filter_expr: Expression) -> Table: ...
    def combine_chunks(self) -> Table: ...
    def to_batches(self) -> list[RecordBatch]: ...

def concat_tables(tables: list[Table]) -> Table: ...

class Array:
    def take(self, indices: Array) -> Array: ...

class Int64Array(Array): ...
class Int8Array(Array): ...

class UnionArray(Array):
    @classmethod
    def from_sparse(cls, type_mask: Array, values: list[Array]) -> UnionArray: ...

def array(values: list[Any], *, type: DataType | None = None) -> Array: ...

class RecordBatch:
    @classmethod
    def from_arrays(
        cls, arrays: list[Array], *, names: Iterable[str]
    ) -> RecordBatch: ...
    def column(self, i: int | str) -> Array: ...

def record_batch(values: list[Array], *, names: list[str]) -> RecordBatch: ...

class Schema:
    def empty_table(self) -> Table: ...

def schema(fields: list[tuple[str, DataType]]) -> Schema: ...
