from typing import Any

import pyarrow as pa

def make_struct(*arrays: pa.Array) -> pa.Array: ...
def is_valid(*array: pa.Array) -> pa.Array: ...
def case_when(cond: pa.Array, *values: int) -> pa.Array: ...
def choose(choice: pa.Int64Array, *arrays: pa.Array) -> pa.Array: ...
def add(left: pa.Array, right: pa.Array) -> pa.Array: ...

class Expression:
    def __le__(self, other: Any) -> Expression: ...
    def __lt__(self, other: Any) -> Expression: ...
    def __and__(self, other: Any) -> Expression: ...
    def __eq__(self, other: Any) -> Expression: ...
    def __or__(self, other: Any) -> Expression: ...
    def __invert__(self) -> Expression: ...

def field(name: str) -> Expression: ...
